import { HobbyId } from '../data/lessonContent';

export type GoalCategory = 'skill' | 'execution';

export type GoalType =
  | 'skill_rating'
  | 'skill_course'
  | 'skill_time'
  | 'skill_distance'
  | 'reading_books'
  | 'reading_minutes'
  | 'reading_pages'
  | 'execution_count';

export interface ToolRecommendation {
  name: string;
  description: string;
  category: string;
  cost: 'free' | 'low' | 'medium' | 'high';
  setup: 'instant' | 'minutes' | 'hours' | 'days';
  effort: 'none' | 'low' | 'medium' | 'high';
  url?: string;
  reason: string;
}

export interface BottleneckAnalysis {
  bottleneck: string;
  severity: 'mild' | 'moderate' | 'severe';
  recommendations: ToolRecommendation[];
  label: string;
}

export type HelpMode = 'milestone' | 'tactical' | 'tools' | 'troubleshoot';

export interface Milestone {
  label: string;
  target: number;
  currentValue: number;
  unit: string;
}

export interface GoalDefinition {
  id: string;
  hobby: HobbyId;
  type: GoalType;
  category: GoalCategory;
  target: number;
  deadline: string;
  startDate: string;
  startingValue: number;
  description: string;
  status: 'active' | 'paused' | 'completed' | 'abandoned';
  difficultyScore?: number;
  targetDifficulty?: number;
  unitLabel?: string;
}

export interface GoalProgressEntry {
  date: string;
  value: number;
  description: string;
  type?: 'task' | 'checkin' | 'bottleneck';
}

export interface DailyGoalContent {
  goalId: string;
  date: string; // YYYY-MM-DD, cache key
  mode: HelpMode;
  learn: {
    title: string;
    body: string;
  };
  doNow: {
    title: string;
    instructions: string;
    estimatedMinutes: number;
    toolRecommendation?: ToolRecommendation;
  };
  /**
   * When true, content was generated by AI from the user's *specific* plan
   * (goal-aware). False = static fallback (goal had no PlanOfAttack yet).
   */
  isFallback: boolean;
  isAIGenerated?: boolean;
  completedAt?: string;
  /** Plain-language reason *why* the system picked today's content strategy.
   * Computed by dailyFocusEngine, safe to show directly in the mode banner. */
  focusReason?: string;
}

export interface PlanStep {
  index: number;             // 0-based
  day: number;               // 1-based day within the goal
  label: string;             // short title e.g. "Read your first 20 pages"
  detail: string;            // what to do
  estimatedMinutes: number;  // time budget for the step
  completed?: boolean;
  completedAt?: string;
}

export interface PlanOfAttack {
  goalId: string;
  generatedAt: string;            // ISO
  source: 'llm' | 'heuristic';
  summary: string;                // 1-line description the user understands
  steps: PlanStep[];
  currentStepIndex: number;       // pointer to today's tile
}

export interface CommitmentRecord {
  text: string;                   // original free-form input
  date: string;                   // YYYY-MM-DD when committed
  action: string;                 // parsed clean action (e.g. "Read 20 pages of book")
  category: 'do_work' | 'log_units' | 'reflect' | 'plan' | 'other';
  estimatedMinutes?: number;
}

export interface GoalProgress {
  goalId: string;
  currentValue: number;
  currentDifficulty?: number;
  lastUpdated: string;
  dailyActions: number;
  streak: number;
  history: GoalProgressEntry[];
  lastBottleneck?: BottleneckAnalysis;
  velocityTrend?: number;
  currentMode: HelpMode;
  milestones: Milestone[];
  currentMilestoneIndex: number;
  dailyContent?: Record<string, DailyGoalContent>; // keyed by date
  dailyCoachHistory?: string[]; // dates coaching was completed
  coachFeedback?: Record<string, 'helpful' | 'skipped' | 'not_helpful'>; // keyed by date
  planOfAttack?: PlanOfAttack;
  /** Today's parsed commitment from the free-form commit input */
  commitment?: CommitmentRecord;
  /** Last week's commitment, surfaced in the card for follow-through */
  yesterdayCommitment?: CommitmentRecord;
  /** Whether the user logged follow-through on yesterday's commitment */
  yesterdayCommitmentHonored?: boolean;
  /** Persistent daily plan (steps + assets) */
  dailyPlan?: DailyPlan;
}

// ── Daily plan types (shared between orchestrator, coach, goal-detail) ──
export interface StepInstruction {
  step: number;
  title: string;
  description: string;
  duration: string;
  type: 'learn' | 'practice' | 'review' | 'log';
  assetRefs: string[];
}

export interface BuiltAsset {
  id: string;
  type: 'research' | 'code' | 'image' | 'deployment' | 'summary';
  title: string;
  description: string;
  action: string;
  content?: string;
  supportsStep: number;
}

export interface DailyPlan {
  steps: StepInstruction[];
  assets: BuiltAsset[];
  focusReason: string;
}

export interface GoalSnapshot {
  definition: GoalDefinition;
  progress: GoalProgress;
  percentComplete: number;
  daysRemaining: number;
  projectedCompletion: 'on_track' | 'ahead' | 'behind';
  unitsRemaining: number;
  dailyRateNeeded: number;
  unitLabel: string;
}
